name: Limpiar repositorio

on:
  push:
    branches:
      - main.js
  pull_request:
    branches:
      - main.js

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Comprobar repositorio
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Usa la versión de Python que necesites

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script de limpieza
      run: |
        python limpiar_repositorio.py
