name: Aplicación Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Comprobar repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: |
        npm install

    - name: Ejecutar pruebas
      run: |
        npm test

    - name: Subir artefacto
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: ./path/to/artifacts

    - name: Configurar SDK de .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Instalar dependencias .NET
      run: |
        dotnet restore

    - name: Ejecutar pruebas .NET
      run: |
        dotnet test

    - name: Subir artefacto .NET
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-test-results
        path: ./path/to/dotnet/test/results
name: Aplicación Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Comprobar repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: |
        npm install

    - name: Ejecutar pruebas
      run: |
        npm test

    - name: Subir artefacto
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: ./path/to/artifacts

    - name: Configurar SDK de .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Instalar dependencias .NET
      run: |
        dotnet restore

    - name: Ejecutar pruebas .NET
      run: |
        dotnet test

    - name: Subir artefacto .NET
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-test-results
        path: ./path/to/dotnet/test/results
