name: Aplicación Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Comprobar repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: |
        npm install

    - name: Ejecutar pruebas
      run: |
        npm test

    - name: Mostrar detalles del error si los hay
      "if: failure()" 
      run: echo "Error: ${{ failure() }}"

    - name: Subir artefacto
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: ruta/a/tus/artefactos

    - name: Configurar SDK de .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
