name: Aplicación Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Comprobar repositorio
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      continue-on-error: true

    - name: Instalar dependencias específicas de spaCy
      run: |
        pip install -U pip setuptools wheel
        pip install -U spacy
        python -m spacy download en_core_web_sm
      continue-on-error: true

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar dependencias de Node.js
      run: |
        npm install

    - name: Ejecutar pruebas
      run: |
        npm test

    - name: Subir artefacto
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: ruta/a/tus/artefactos

    - name: Configurar SDK de .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
